[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=development npm install && npx nx build api --configuration=production"

[deploy]
startCommand = "node apps/api/dist/main.js"
restartPolicyType = "on_failure"
