[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && ./node_modules/.bin/nx build api --configuration=production"

[deploy]
startCommand = "node apps/api/dist/main.js"
restartPolicyType = "on_failure"
